### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by Hanz-212** [evanhyd/TetrioDestroyer#1]
how to run this step by step and play tetrio

**Comment by evanhyd** [comment]
Hi @Hanz-212 
To play on tetrio, you need to use the following configuration in your setting
![image](https://github.com/evanhyd/TetrioDestroyer/assets/38232257/68b0b494-095d-4c11-9fcd-0e9e47baf781)
![image](https://github.com/evanhyd/TetrioDestroyer/assets/38232257/86589a7d-8ff0-4db2-a525-7115e464e3bd)
![image](https://github.com/evanhyd/TetrioDestroyer/assets/38232257/6449888b-5f14-498d-9962-cfdb04df3298)
and then make sure in the main() function, it is calling the PlayTetrio() function with a searching depth of 3-4

Tetrio limits the keyboard input speed and will occasionally disconnect you from the game if the delay between each keypress is too short, hence there would be a 200ms hardcoded delay between each piece placement. Therefore I am migrating this engine to another popular online Tetris platform  (Jstris) to bypass this issue.

With a depth of 4, the engine can easily place up to 8000 ~ 25000 pieces without dying.

This project is not even close to completion. You are welcome to check back later in a few weeks since I will use alternative and more efficient methods to train my bot.
